In [2]:
1+1

2

In [4]:
import os
os.getcwd()

'C:\\Users\\bhand\\Desktop\\Data Scientist\\DataScienceProjects'

In [9]:
import os
os.chdir('C:\\Users\\bhand\\Desktop\\Data Scientist\\DataScienceProjects\\BigMartSalesPractices\\src\\Data')

In [11]:
import os
os.getcwd()

'C:\\Users\\bhand\\Desktop\\Data Scientist\\DataScienceProjects\\BigMartSalesPractices\\src\\Data'

In [17]:
import pandas as pd
import numpy as np

#Read files:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
#print(train)
print(test)

     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDW58       20.750          Low Fat         0.007565
1              FDW14        8.300              reg         0.038428
2              NCN55       14.600          Low Fat         0.099575
3              FDQ58        7.315          Low Fat         0.015388
4              FDY38          NaN          Regular         0.118599
5              FDH56        9.800          Regular         0.063817
6              FDL48       19.350          Regular         0.082602
7              FDC48          NaN          Low Fat         0.015782
8              FDN33        6.305          Regular         0.123365
9              FDA36        5.985          Low Fat         0.005698
10             FDT44       16.600          Low Fat         0.103569
11             FDQ56        6.590          Low Fat         0.105811
12             NCC54          NaN          Low Fat         0.171079
13             FDU11        4.785          Low Fat         0.092738
14             DRL59       16.750               LF         0.021206
15             FDM24        6.135          Regular         0.079451
16             FDI57       19.850          Low Fat         0.054135
17             DRC12       17.850          Low Fat         0.037981
18             NCM42          NaN          Low Fat         0.028184
19             FDA46       13.600          Low Fat         0.196898
20             FDA31        7.100          Low Fat         0.109920
21             NCJ31       19.200          Low Fat         0.182619
22             FDG52       13.650               LF         0.065631
23             NCL19          NaN          Low Fat         0.027447
24             FDS10       19.200          Low Fat         0.035179
25             FDX22        6.785          Regular         0.038455
26             NCF19       13.000          Low Fat         0.035102
27             NCE06        5.825          Low Fat         0.091485
28             DRC27       13.800          Low Fat         0.058102
29             FDE21       12.800               LF         0.022940
...              ...          ...              ...              ...
5651           FDD23        9.500          Regular         0.048645
5652           FDP32        6.650          Low Fat         0.087847
5653           FDO31        6.760          Regular         0.028977
5654           FDQ57        7.275          Low Fat         0.000000
5655           FDX32          NaN          Regular         0.099375
5656           FDC39          NaN          Low Fat         0.158425
5657           FDU55       16.200          Low Fat         0.035911
5658           FDL45       15.600          Low Fat         0.037656
5659           DRK37        5.000          Low Fat         0.044073
5660           FDK22        9.800          Low Fat         0.026065
5661           DRG37          NaN          Low Fat         0.000000
5662           FDK22        9.800          Low Fat         0.026234
5663           DRH36       16.200          Low Fat         0.033516
5664           DRC36       13.000          Regular         0.045168
5665           DRE03          NaN          Low Fat         0.024110
5666           FDF34        9.300          Regular         0.014019
5667           FDZ22        9.395          Low Fat         0.045270
5668           FDC44       15.600          Low Fat         0.288892
5669           FDN31          NaN          Low Fat         0.072529
5670           FDO03       10.395          Regular         0.037092
5671           FDA01       15.000              reg         0.054463
5672           NCH42        6.860          Low Fat         0.036594
5673           FDF46        7.070          Low Fat         0.094053
5674           DRL35       15.700          Low Fat         0.030704
5675           FDW46       13.000          Regular         0.070411
5676           FDB58       10.500          Regular         0.013496
5677           FDD47        7.600          Regular         0.142991
5678           NCO17       10.000          Low Fat         0.073529
5679           FDJ26       15.300          Regular         0.000000
5680           FDU37        9.500          Regular         0.104720

                  Item_Type  Item_MRP Outlet_Identifier  \
0               Snack Foods  107.8622            OUT049
1                     Dairy   87.3198            OUT017
2                    Others  241.7538            OUT010
3               Snack Foods  155.0340            OUT017
4                     Dairy  234.2300            OUT027
5     Fruits and Vegetables  117.1492            OUT046
6              Baking Goods   50.1034            OUT018
7              Baking Goods   81.0592            OUT027
8               Snack Foods   95.7436            OUT045
9              Baking Goods  186.8924            OUT017
10    Fruits and Vegetables  118.3466            OUT017
11    Fruits and Vegetables   85.3908            OUT045
12       Health and Hygiene  240.4196            OUT019
13                   Breads  122.3098            OUT049
14              Hard Drinks   52.0298            OUT013
15             Baking Goods  151.6366            OUT049
16                  Seafood  198.7768            OUT045
17              Soft Drinks  192.2188            OUT018
18                Household  109.6912            OUT027
19              Snack Foods  193.7136            OUT010
20    Fruits and Vegetables  175.0080            OUT013
21                   Others  239.9196            OUT035
22             Frozen Foods   47.7402            OUT046
23                   Others  142.3470            OUT019
24              Snack Foods  180.7318            OUT035
25              Snack Foods  209.4928            OUT010
26                Household   47.6034            OUT035
27                Household  161.3894            OUT046
28                    Dairy  244.6802            OUT046
29    Fruits and Vegetables  116.5492            OUT035
...                     ...       ...               ...
5651          Starchy Foods  186.1898            OUT013
5652  Fruits and Vegetables  126.7678            OUT045
5653  Fruits and Vegetables   80.2960            OUT035
5654            Snack Foods  144.5760            OUT013
5655  Fruits and Vegetables  143.6786            OUT027
5656                  Dairy  207.8296            OUT027
5657  Fruits and Vegetables  261.3278            OUT046
5658            Snack Foods  123.4704            OUT013
5659            Soft Drinks  188.8530            OUT049
5660            Snack Foods  215.3850            OUT013
5661            Soft Drinks  155.7972            OUT027
5662            Snack Foods  214.3850            OUT017
5663            Soft Drinks   72.8696            OUT018
5664            Soft Drinks  173.4054            OUT018
5665                  Dairy   46.0718            OUT027
5666            Snack Foods  196.9084            OUT046
5667            Snack Foods   82.1250            OUT046
5668  Fruits and Vegetables  115.1518            OUT010
5669  Fruits and Vegetables  188.0530            OUT027
5670                   Meat  229.4352            OUT017
5671                 Canned   59.5904            OUT049
5672              Household  231.1010            OUT049
5673            Snack Foods  116.0834            OUT018
5674            Hard Drinks   43.2770            OUT046
5675            Snack Foods   63.4484            OUT049
5676            Snack Foods  141.3154            OUT046
5677          Starchy Foods  169.1448            OUT018
5678     Health and Hygiene  118.7440            OUT045
5679                 Canned  214.6218            OUT017
5680                 Canned   79.7960            OUT045

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1
1                          2007         NaN               Tier 2
2                          1998         NaN               Tier 3
3                          2007         NaN               Tier 2
4                          1985      Medium               Tier 3
5                          1997       Small               Tier 1
6                          2009      Medium               Tier 3
7                          1985      Medium               Tier 3
8                          2002         NaN               Tier 2
9                          2007         NaN               Tier 2
10                         2007         NaN               Tier 2
11                         2002         NaN               Tier 2
12                         1985       Small               Tier 1
13                         1999      Medium               Tier 1
14                         1987        High               Tier 3
15                         1999      Medium               Tier 1
16                         2002         NaN               Tier 2
17                         2009      Medium               Tier 3
18                         1985      Medium               Tier 3
19                         1998         NaN               Tier 3
20                         1987        High               Tier 3
21                         2004       Small               Tier 2
22                         1997       Small               Tier 1
23                         1985       Small               Tier 1
24                         2004       Small               Tier 2
25                         1998         NaN               Tier 3
26                         2004       Small               Tier 2
27                         1997       Small               Tier 1
28                         1997       Small               Tier 1
29                         2004       Small               Tier 2
...                         ...         ...                  ...
5651                       1987        High               Tier 3
5652                       2002         NaN               Tier 2
5653                       2004       Small               Tier 2
5654                       1987        High               Tier 3
5655                       1985      Medium               Tier 3
5656                       1985      Medium               Tier 3
5657                       1997       Small               Tier 1
5658                       1987        High               Tier 3
5659                       1999      Medium               Tier 1
5660                       1987        High               Tier 3
5661                       1985      Medium               Tier 3
5662                       2007         NaN               Tier 2
5663                       2009      Medium               Tier 3
5664                       2009      Medium               Tier 3
5665                       1985      Medium               Tier 3
5666                       1997       Small               Tier 1
5667                       1997       Small               Tier 1
5668                       1998         NaN               Tier 3
5669                       1985      Medium               Tier 3
5670                       2007         NaN               Tier 2
5671                       1999      Medium               Tier 1
5672                       1999      Medium               Tier 1
5673                       2009      Medium               Tier 3
5674                       1997       Small               Tier 1
5675                       1999      Medium               Tier 1
5676                       1997       Small               Tier 1
5677                       2009      Medium               Tier 3
5678                       2002         NaN               Tier 2
5679                       2007         NaN               Tier 2
5680                       2002         NaN               Tier 2

            Outlet_Type
0     Supermarket Type1
1     Supermarket Type1
2         Grocery Store
3     Supermarket Type1
4     Supermarket Type3
5     Supermarket Type1
6     Supermarket Type2
7     Supermarket Type3
8     Supermarket Type1
9     Supermarket Type1
10    Supermarket Type1
11    Supermarket Type1
12        Grocery Store
13    Supermarket Type1
14    Supermarket Type1
15    Supermarket Type1
16    Supermarket Type1
17    Supermarket Type2
18    Supermarket Type3
19        Grocery Store
20    Supermarket Type1
21    Supermarket Type1
22    Supermarket Type1
23        Grocery Store
24    Supermarket Type1
25        Grocery Store
26    Supermarket Type1
27    Supermarket Type1
28    Supermarket Type1
29    Supermarket Type1
...                 ...
5651  Supermarket Type1
5652  Supermarket Type1
5653  Supermarket Type1
5654  Supermarket Type1
5655  Supermarket Type3
5656  Supermarket Type3
5657  Supermarket Type1
5658  Supermarket Type1
5659  Supermarket Type1
5660  Supermarket Type1
5661  Supermarket Type3
5662  Supermarket Type1
5663  Supermarket Type2
5664  Supermarket Type2
5665  Supermarket Type3
5666  Supermarket Type1
5667  Supermarket Type1
5668      Grocery Store
5669  Supermarket Type3
5670  Supermarket Type1
5671  Supermarket Type1
5672  Supermarket Type1
5673  Supermarket Type2
5674  Supermarket Type1
5675  Supermarket Type1
5676  Supermarket Type1
5677  Supermarket Type2
5678  Supermarket Type1
5679  Supermarket Type1
5680  Supermarket Type1

[5681 rows x 11 columns]

In [18]:
train['source']='train'
test['source']='test'
data = pd.concat([train, test],ignore_index=True)
print train.shape, test.shape, data.shape

(8523, 13) (5681, 12) (14204, 13)

In [20]:
data.apply(lambda x: sum(x.isnull()))

Item_Fat_Content                0
Item_Identifier                 0
Item_MRP                        0
Item_Outlet_Sales            5681
Item_Type                       0
Item_Visibility                 0
Item_Weight                  2439
Outlet_Establishment_Year       0
Outlet_Identifier               0
Outlet_Location_Type            0
Outlet_Size                  4016
Outlet_Type                     0
source                          0
dtype: int64

In [21]:
data.describe()

,Item_MRP,Item_Outlet_Sales,Item_Visibility,Item_Weight,Outlet_Establishment_Year
count,14204.000000,8523.000000,14204.000000,11765.000000,14204.000000
mean,141.004977,2181.288914,0.065953,12.792854,1997.830681
std,62.086938,1706.499616,0.051459,4.652502,8.371664
min,31.290000,33.290000,0.000000,4.555000,1985.000000
25%,94.012000,834.247400,0.027036,8.710000,1987.000000
50%,142.247000,1794.331000,0.054021,12.600000,1999.000000
75%,185.855600,3101.296400,0.094037,16.750000,2004.000000
max,266.888400,13086.964800,0.328391,21.350000,2009.000000